# Generated by Django 5.0.6 on 2024-06-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_cust',
            old_name='zipcode',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='record_cust',
            name='state',
        ),
    ]
