# Generated by Django 5.0.6 on 2024-06-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_rename_zipcode_record_cust_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record_cust',
            name='address',
        ),
        migrations.AddField(
            model_name='record_cust',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
    ]
