# Generated by Django 5.0.6 on 2024-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_remove_record_cust_address_record_cust_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('city', models.CharField(max_length=50)),
                ('organisation', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
            ],
        ),
    ]
