# Generated by Django 5.0.6 on 2024-07-01 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_event_ticketinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='relationship',
        ),
    ]
